CREATE TABLE roles (
    id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

INSERT INTO roles (name)
VALUES ('user');

ALTER TABLE users 
ADD COLUMN role_id SMALLINT NOT NULL REFERENCES roles(id);