ALTER TABLE users
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE users
ALTER COLUMN id TYPE UUID
USING gen_random_uuid();

ALTER TABLE users
ALTER COLUMN id SET DEFAULT gen_random_uuid();

DROP SEQUENCE IF EXISTS users_id_seq;
