services:
  migrate:
      image: migrate/migrate:v4.18.3
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - ./db/migrations:/migrations
      command:
        [
          "-path", "/migrations",
          "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable",
          "up"
        ]
      networks:
        - app

  server:
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
