// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ByEmail(ctx context.Context, lower string) (ByEmailRow, error)
	ByName(ctx context.Context, name string) (ByNameRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteUser(ctx context.Context, id int32) error
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
}

var _ Querier = (*Queries)(nil)
