// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckUserExists(ctx context.Context, arg CheckUserExistsParams) (CheckUserExistsRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteTokenHash(ctx context.Context, tokenHash string) error
	GetTokenHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTokenUserID(ctx context.Context, userID uuid.UUID) (GetTokenUserIDRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByLogin(ctx context.Context, email string) (GetUserByLoginRow, error)
}

var _ Querier = (*Queries)(nil)
