// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refrash_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token_hash,
    expires_at
)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTokenHash = `-- name: DeleteTokenHash :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteTokenHash, tokenHash)
	return err
}

const getTokenHash = `-- name: GetTokenHash :one
SELECT
    id,
    user_id,
    token_hash,
    created_at,
    expires_at,
    revoked
FROM refresh_tokens
WHERE token_hash = $1
  AND revoked = FALSE
  AND expires_at > NOW()
`

func (q *Queries) GetTokenHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getTokenHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getTokenUserID = `-- name: GetTokenUserID :one
SELECT
    id,
    token_hash,
    created_at,
    expires_at,
    revoked
FROM refresh_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetTokenUserIDRow struct {
	ID        uuid.UUID          `json:"id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
}

func (q *Queries) GetTokenUserID(ctx context.Context, userID uuid.UUID) (GetTokenUserIDRow, error) {
	row := q.db.QueryRow(ctx, getTokenUserID, userID)
	var i GetTokenUserIDRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}
